stepshop/authapp/urls.py
from django.urls import path

from .views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

stepshop/stepshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index, contacts, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

# благодаря этой команде все картинки при добавление добавляются в папку media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

class ShopUser(AbstractUser):
    avatar = models.ImageField(
        upload_to='users_avatars',
        blank=True,
        verbose_name='Аватарка',
    )

    age = models.PositiveIntegerField(
        verbose_name='возраст',
    )

stepshop/authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from authapp.models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data_age = self.cleaned_data['age']
        if data_age < 16:
            raise forms.ValidationError('Вы слишком молоды!')

        return data_age


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'email', 'age', 'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data_age = self.cleaned_data['age']
        if data_age < 16:
            raise forms.ValidationError('Не достоин!')

        return data_age

stepshop/authapp/views.py
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import render


from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm
from django.urls import reverse


def login(request):
    title = 'вход'

    login_form = ShopUserLoginForm(data=request.POST)
    _next = request.GET['next'] if 'next' in request.GET.keys() else ''

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            return HttpResponseRedirect(reverse('index'))

    context = {
        'title': title,
        'login_form': login_form,
        'next': _next,
    }

    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    title = 'регистрация'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))

    else:
        register_form = ShopUserRegisterForm()

    context = {
        'title': title,
        'register_form': register_form,
    }

    return render(request, 'authapp/register.html', context)


def edit(request):
    title = 'редактирование'

    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)

        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))

    else:
        edit_form = ShopUserEditForm(instance=request.user)

    context = {
        'title': title,
        'edit_form': edit_form,
    }

    return render(request, 'authapp/edit.html', context)

stepshop/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    <link href="{% static '/stepshop/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/stepshop/assets/css/fontawesome.css' %}">
    {% block css %}
    {% endblock %}


</head>
<body>

<div class="container">
    <div class="login">
        <div class="h2 text-center head">
            Вход в систему
        </div>
        {% block content %}
        {% endblock %}
    </div>
</div>
<script src="{% static '/stepshop/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static '/stepshop/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


<!-- Additional Scripts -->
{% block js %}
{% endblock %}
</body>
</html>

stepshop/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}
{% load default_image_tags %}

{% block content %}
<div class="mx-auto col-4">
    <div class="row">
        <div class="user_avatar">
            <img width="100px" height="100px" src="{{ user.avatar|default_avatar_image }}" alt="{{ user.username }}">
        </div>
    </div>
    <div class="row">
        <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ edit_form.as_p }}
            <button type="submit" class="btn btn-primary form-control">Сохранить</button>
        </form>
        <button class="btn btn-round form-control">
            <a href="{% url 'index' %}">на главную</a>
        </button>
    </div>
</div>
{% endblock %}

stepshop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}


<div class="container">
    <div class="row">
        <div class="mx-auto col-3">
            <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
                {% csrf_token %}
                {% if next %}
                    <input type="hidden" name="next" value="">
                {% endif %}
                {{ login_form.as_p }}
                <button type="submit" class="btn btn-primary">Войти</button>
            </form>
        </div>
    </div>
    <button class="btn btn-round form-control form-control">
        <a href="{% url 'auth:register' %}">Зарегистрироваться</a>
    </button>
</div>
{% endblock %}

stepshop/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
<div class="mx-auto col-3">
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ register_form.as_p }}
        <button type="submit" class="btn btn-primary">Зарегестрироваться</button>
    </form>
</div>
{% endblock %}