stepshop/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp
from adminapp.views import UserListView, UserCreateView, UserUpdateView, UserDeleteView, \
                           CategoryListView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView, \
                           ProductsListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
                           ProductDeleteView


app_name = 'adminapp'

urlpatterns = [
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/read/', UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', CategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', ProductsListView.as_view(), name='products'),
    path('products/read/<int:pk>/', ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
]

stepshop/authapp/urls.py
from django.urls import path

from .views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

stepshop/stepshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index, contacts, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

# благодаря этой команде все картинки при добавление добавляются в папку media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True,
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    is_active = models.BooleanField(
        default=True,
        verbose_name='Активный',
    )

    def __str__(self):
        return self.name or f'Id категории - {self.pk}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        verbose_name='категория'
    )

    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128,
    )

    image = models.ImageField(
        upload_to='product_images',
        blank=True,
        verbose_name='изображение',
    )

    short_desc = models.CharField(
        verbose_name='краткое описание',
        max_length=128,
        blank=True,
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    price = models.DecimalField(
        verbose_name='цена',
        max_digits=8,
        decimal_places=2,
        default=0,
    )

    quantity = models.PositiveIntegerField(
        verbose_name='количество товара на складе',
        default=0,
    )

    is_active = models.BooleanField(
        default=True,
        verbose_name='Активный',
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name or f'Id продукта - {self.pk}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

stepshop/adminapp/forms.py
from django import forms

from mainapp.models import ProductCategory, Product


class ProductCategoryCreateForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

stepshop/adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from adminapp.forms import ProductCategoryCreateForm, ProductCategoryEditForm, ProductEditForm
from authapp.forms import ShopUserRegisterForm, ShopUserEditForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


class UserListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    context_object_name = 'objects'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['title'] = 'админка | пользователи'
        # context.update({'title': 'админка | пользователи'})  # можно и так
        return context

    def get_queryset(self):
        return ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')


# @user_passes_test(lambda u: u.is_superuser)
# def users(request):
#     title = 'админка | пользователи'
#
#     user_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
#
#     context = {
#         'title': title,
#         'objects': user_list,
#     }
#
#     return render(request, 'adminapp/users.html', context)


class UserCreateView(CreateView):
    model = ShopUser
    form_class = ShopUserRegisterForm
    template_name = 'adminapp/users/user_create.html'
    success_url = reverse_lazy('admin_staff:users')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['title'] = 'админка | создать пользователя'
        return context


# def user_create(request):
#     title = 'админка | создать пользователя'
#
#     if request.method == 'POST':
#         user_form = ShopUserRegisterForm(request.POST, request.FILES)
#
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:users'))
#
#     else:
#         user_form = ShopUserRegisterForm()
#
#     context = {
#         'title': title,
#         'user_form': user_form,
#     }
#
#     return render(request, 'adminapp/users/user_create.html', context)


class UserUpdateView(UpdateView):
    model = ShopUser
    form_class = ShopUserEditForm
    template_name = 'adminapp/users/user_update.html'
    success_url = reverse_lazy('admin_staff:users')
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['title'] = 'админка | редактировать пользователя'
        return context


# def user_update(request, pk):
#     title = 'админка | редактировать пользователя'
#
#     edit_user = get_object_or_404(ShopUser, id=pk)
#
#     if request.method == 'POST':
#         edit_form = ShopUserEditForm(request.POST, request.FILES, instance=edit_user)
#
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:users'))
#
#     else:
#         edit_form = ShopUserEditForm(instance=edit_user)
#
#     context = {
#         'title': title,
#         'edit_form': edit_form,
#         'edit_user': edit_user,
#     }
#
#     return render(request, 'adminapp/users/user_update.html', context)


class UserDeleteView(DeleteView):
    model = ShopUser
    context_object_name = 'user_to_delete'
    template_name = 'adminapp/users/user_delete.html'
    success_url = reverse_lazy('admin_staff:users')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


# def user_delete(request, pk):
#     title = 'админка | удаление пользователя'
#
#     user = get_object_or_404(ShopUser, id=pk)
#
#     if request.method == 'POST':
#         user.is_active = False
#         user.save()
#         return HttpResponseRedirect(reverse('admin_staff:users'))
#
#     context = {
#         'title': title,
#         'user_to_delete': user,
#     }
#
#     return render(request, 'adminapp/users/user_delete.html', context)


class CategoryListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'
    context_object_name = 'objects'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['title'] = 'админка | категории'
        return context


# @user_passes_test(lambda u: u.is_staff)
# def categories(request):
#     title = 'админка | категории'
#
#     categories_list = ProductCategory.objects.all()
#
#     context = {
#         'title': title,
#         'objects': categories_list,
#     }
#
#     return render(request, 'adminapp/categories.html', context)


class CategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/categories/category_create.html'
    form_class = ProductCategoryCreateForm
    success_url = reverse_lazy('admin_staff:categories')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['title'] = 'админка | создать категорию'
        return context


# def category_create(request):
#     title = 'админка | создать категорию'
#
#     if request.method == 'POST':
#         category_form = ProductCategoryCreateForm(request.POST, request.FILES)
#
#         if category_form.is_valid():
#             category_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:categories'))
#
#     else:
#         category_form = ProductCategoryCreateForm()
#
#     context = {
#         'title': title,
#         'category_form': category_form,
#     }
#
#     return render(request, 'adminapp/categories/category_create.html', context)


class CategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/categories/category_update.html'
    form_class = ProductCategoryEditForm
    success_url = reverse_lazy('admin_staff:categories')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['title'] = 'админка | редактировать категорию'
        return context


# def category_update(request, pk):
#     title = 'админка | редактировать категорию'
#
#     edit_category = get_object_or_404(ProductCategory, id=pk)
#
#     if request.method == 'POST':
#         edit_form = ProductCategoryEditForm(request.POST, request.FILES, instance=edit_category)
#
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:categories'))
#
#     else:
#         edit_form = ProductCategoryEditForm(instance=edit_category)
#
#     context = {
#         'title': title,
#         'edit_form': edit_form,
#         'edit_category': edit_category,
#     }
#
#     return render(request, 'adminapp/categories/category_update.html', context)


class CategoryDeleteView(DeleteView):
    model = ProductCategory
    context_object_name = 'category_to_delete'
    template_name = 'adminapp/categories/category_delete.html'
    success_url = reverse_lazy('admin_staff:categories')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


# def category_delete(request, pk):
#     title = 'админка | удаление категории'
#
#     category = get_object_or_404(ProductCategory, id=pk)
#
#     if request.method == 'POST':
#         category.is_active = False
#         category.save()
#         return HttpResponseRedirect(reverse('admin_staff:categories'))
#
#     context = {
#         'title': title,
#         'category_to_delete': category,
#     }
#
#     return render(request, 'adminapp/categories/category_delete.html', context)


class ProductsListView(ListView):
    model = Product
    template_name = 'adminapp/products.html'
    context_object_name = 'product_list'
    paginate_by = 3

    def get_queryset(self):
        return Product.objects.filter(category__pk=self.kwargs.get('pk')).order_by('name')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        category = get_object_or_404(ProductCategory, pk=self.kwargs.get('pk'))

        context['title'] = 'админка | продукты'
        context['category'] = category
        return context


# @user_passes_test(lambda u: u.is_staff)
# def products(request, pk):
#     title = 'админка | продукты'
#
#     category = get_object_or_404(ProductCategory, id=pk)
#     products_list = Product.objects.filter(category__pk=pk).order_by('name')
#
#     context = {
#         'title': title,
#         'category': category,
#         'objects': products_list,
#     }
#
#     return render(request, 'adminapp/products.html', context)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product/product_read.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['title'] = 'админка | продукты подробнее'
        return context


# def product_read(request, pk):
#     title = 'админка | продукты подробнее'
#
#     product = get_object_or_404(Product, id=pk)
#
#     context = {
#         'title': title,
#         'product': product,
#     }
#
#     return render(request, 'adminapp/product/product_read.html', context)


class ProductCreateView(CreateView):
    model = Product
    template_name = 'adminapp/product/product_create.html'
    form_class = ProductEditForm

stepshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
{% load default_image_tags %}

<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'adminapp/style.css' %}">
        <link rel="stylesheet" type="text/css" href='https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css'>
        <link rel="stylesheet" type="text/css" href="{% static 'stepshop/assets/css/font-awesome.css' %}">

        <link rel="stylesheet" href="{% static 'mainapp/style.css' %}">

    {% block css %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'adminapp/script.js' %}"></script>

    {% block js %}
    {% endblock %}
</head>
<body id="body-pd">
<header class="header" id="header">
    <div class="header_toggle"><i class='bx bx-menu' id="header-toggle"></i></div>
    <div class="header_img"><img src="/media/{{ user.avatar|default_avatar_image }}" alt=""></div>
<!--    <div class="header_img"><img src="/media/{{ user.avatar|default:'avatar-default.png' }}" alt=""></div>-->
</header>
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div>
            <a href="{% url 'index' %}" class="nav_logo">
                <i class='bx bx-layer nav_logo-icon'></i>
                <span class="nav_logo-name">Панель контроля</span>
            </a>
            {% include 'adminapp/inсludes/inc_admin_menu.html' %}
        </div>
        <a href="{% url 'auth:logout' %}" class="nav_link">
            <i class='bx bx-log-out nav_icon'></i>
            <span class="nav_name">
            Выход
            </span>
        </a>
    </nav>
</div>
<!--Container Main start-->
<div class="height-100 bg-light">
    {% block content %}
    {% endblock %}
</div>
<!--Container Main end-->
</body>
</html>

stepshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Категории</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fa fa-table mr-1"></i>
                Категории продуктов
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for category in objects %}
                            <tr {% if not category.is_active %} style="opacity: 0.5;" {% endif %}>
                                <td><a href="{% url 'admin_staff:products' category.id %}"
                                       style="color: dodgerblue">{{ category.name }}</a></td>
                                <td>
                                    <a {% if not category.is_active %}
                                       class="invisible" {% endif %}
                                       href="{% url 'admin_staff:category_update' pk=category.id %}">
                                        Изменить
                                    </a>
                                </td>
                                <td>
                                    <a {% if not category.is_active %}
                                       class="invisible" {% endif %}
                                       href="{% url 'admin_staff:category_delete' pk=category.id %}">
                                        Удалить
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:category_create' %}">
                    <button class="btn btn-success">Создать категорию</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

stepshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load default_image_tags %}


{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Продукты</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fa fa-table mr-1"></i>
                Продукты категории {{ category.name }}
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Название</th>
                            <th>Описание</th>
                            <th>Количество</th>
                            <th>Стоимость</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for product in product_list %}
                            <tr {% if not product.is_active %} style="opacity: 0.5;" {% endif %}>
                                <td><a href="{% url 'admin_staff:product_read' product.id %}"
                                       style="color: dodgerblue">{{ product.name }}</a></td>
                                <td>{{ product.short_desc }}</td>
                                <td>{{ product.quantity }}</td>
                                <td>${{ product.price }}</td>
                                <td>
                                    <a href="{% url 'admin_staff:product_update' pk=product.id %}">
                                        Редактировать
                                    </a>
                                </td>
                                <td>
                                    <a {% if not product.is_active %}class="invisible" {% endif %}
                                       href="{% url 'admin_staff:product_delete' pk=product.id %}">
                                        Удалить
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>

                <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; первая</a> |
                            <a href="?page={{ page_obj.previous_page_number }}">предыдущая</a>
                        {% endif %}

                        <span class="current">
                            | Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }} |
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">следующая</a> |
                            <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:product_create' category.pk %}">
                    <button class="btn btn-success">Создать продукт</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

stepshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Пользователи
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for user in objects %}
                        <tr {% if not user.is_active %} style="opacity: 0.5;" {% endif %}>
                            <td><a href="{% url 'admin_staff:user_update' user.pk %}"
                                   style="color: dodgerblue">{{ user.username }}</a></td>
                            <td>{{ user.first_name }}</td>
                            <td>{{ user.email }}</td>
                            <td class="text-center">
                                {% if user.is_staff %}
                                <span>Да</span>
                                {% else %}
                                <span>Нет</span>
                                {% endif %}
                            </td>
                            <td>{{ user.last_login }}</td>
                            <td>
                                <a {% if not user.is_active %}
                                   class="invisible" {% endif %}
                                   href="{% url 'admin_staff:user_delete' pk=user.id %}">
                                    <span>Удалить</span>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:user_create' %}">
                    <button class="btn btn-success">Создать пользователя</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}