stepshop/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp
from adminapp.views import UserListView, UserCreateView, UserUpdateView, UserDeleteView, \
                           CategoryListView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView, \
                           ProductsListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
                           ProductDeleteView


app_name = 'adminapp'

urlpatterns = [
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/read/', UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', CategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', ProductsListView.as_view(), name='products'),
    path('products/read/<int:pk>/', ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
]

stepshop/authapp/urls.py
from django.urls import path

from .views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

stepshop/basketapp/urls.py
from django.urls import path

from basketapp.views import basket, basket_add, basket_remove, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>', basket_add, name='add'),
    path('remove/<int:pk>', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit'),
]

stepshop/mainapp/urls.py
from django.urls import path

from .views import products, product

app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
    path('page/<int:page>', products, name='page'),
    path('category/<int:pk>/', products, name='category'),
    path('category/<int:pk>/page/<int:page>/', products, name='category_page'),
    path('product/<int:pk>', product, name='product'),
]

stepshop/stepshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index, contacts, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

# благодаря этой команде все картинки при добавление добавляются в папку media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/stepshop/views.py
from django.shortcuts import render

from basketapp.models import Basket
from mainapp.models import Product


def index(request):
    title = 'главная'

    products = Product.objects.filter(category__is_active=True)[:4]

    basket = []

    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    context = {
        'title': title,
        'products': products,
        'basket': basket,
    }

    return render(request, 'stepshop/index.html', context)


def contacts(request):
    title = 'контакты'

    basket = []

    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    context = {
        'title': title,
        'basket': basket,
    }

    return render(request, 'stepshop/contact.html', context)


def about(request):
    title = 'о нас'

    basket = []

    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    context = {
        'title': title,
        'basket': basket,
    }

    return render(request, 'stepshop/about.html', context)

stepshop/stepshop/templates/stepshop/about.html
{% extends 'stepshop/base.html' %}
{% load static %}

{% block title %}О нас{% endblock %}

{% block css %}
    <link rel="stylesheet" href="/static/stepshop/assets/css/flex-slider.css">
{% endblock %}

{% block content %}
    <!-- Page Content -->
    <!-- About Page Starts Here -->
    <div class="about-page">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>О нас</h1>
            </div>
          </div>
          <div class="col-md-6">
            <div class="left-image">
              <img src="{% static '/stepshop/assets/images/about-us.jpg' %}" alt="">
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <h4>Phasellus vel interdum elit</h4>
              <p><a href="https://www.pexels.com/photo/group-of-people-raising-right-hand-1059120/"></a>Мы</div>
          </div>
        </div>
      </div>
    </div>
    <!-- About Page Ends Here -->
{% endblock %}

stepshop/stepshop/templates/stepshop/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet">

    <title>
        {% block title %}
        {{ title|title }} - EVILBLOODMACHINE INC
        {% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static '/stepshop/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static '/stepshop/assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static '/stepshop/assets/css/tooplate-main.css' %}">
    <link rel="stylesheet" href="{% static '/stepshop/assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'mainapp/style.css' %}">


    {% block css %}
    {% endblock %}
    <!--
Tooplate 2114 Pixie
https://www.tooplate.com/view/2114-pixie
-->
</head>

<body>

<!-- Pre Header -->
<div id="pre-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                {% if user.is_staff %}
                <a href="{% url 'admin_staff:users' %}" class="admin-panel"></a>
                {% elif user.is_superuser %}
                 <a href="{% url 'admin_staff:users' %}" class="admin-panel"></a>
                {% endif %}

                {% if user.is_authenticated %}
<!--                <span>-->
<!--                    <a href="{% url 'auth:edit' %}" style="color:white; font-family:monospace">-->
<!--                        {{ user.first_name|default:user.username }}-->
<!--                    </a>-->
<!--                </span>-->
                <a href="{% url 'auth:edit' %}" class="edit-panel"></a>
<!--                <span>-->
<!--                     <a href="{% url 'auth:logout' %}" style="color:white; font-family:monospace">-->
<!--                        Выйти-->
<!--                    </a>-->
<!--                </span>-->
                <a href="{% url 'auth:logout' %}" class="logout-panel"></a>
                {% else %}
<!--                <span>-->
<!--                     <a href="{% url 'auth:login' %}" style="color:white; font-family:monospace">-->
<!--                        Войти-->
<!--                    </a>-->
<!--                </span>-->
                <a href="{% url 'auth:login' %}" class="logout-panel"></a>
                {% endif %}

                {% if basket %}
                    {% if user.is_authenticated %}
                        {% if basket.0.total_quantity > 0 %}
                            <a href="{% url 'basket:view' %}" class="basket">
                                <span>{{ basket.0.total_quantity }}</span>
                            </a>
                            <span class="price">{{ basket.0.total_cost|floatformat:0 }}$</span>
                        {% endif %}
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- Navigation -->
{% include 'stepshop/includes/main_menu.html' %}

{% block content %}
Блок из base.html
{% endblock %}


<!-- Sub Footer Starts Here -->
<div class="sub-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="copyright-text">
                    <p>Copyright &copy; 2019 - {% now "Y" %} EVILBLOODMACHINE INC.

                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Sub Footer Ends Here -->


<!-- Bootstrap core JavaScript -->
<script src="{% static '/stepshop/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static '/stepshop/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


<!-- Additional Scripts -->
<script src="{% static '/stepshop/assets/js/custom.js' %}"></script>
<script src="{% static '/stepshop/assets/js/owl.js' %}"></script>


<script language="text/Javascript">
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }










</script>
{% block js %}
{% endblock %}


</body>

</html>

stepshop/stepshop/templates/stepshop/contact.html
{% extends 'stepshop/base.html' %}
{% load static %}

{% block title %}Контакты{% endblock %}

{% block css %}
  <link rel="stylesheet" href="/static/stepshop/assets/css/flex-slider.css">
{% endblock %}

{% block content %}
    <!-- Page Content -->
    <!-- About Page Starts Here -->
    <div class="contact-page">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>Свяжитесь с нами</h1>
            </div>
          </div>
          <div class="col-md-6">
            <div id="map">
            		<!-- How to change your own map point
                           1. Go to Google Maps
                           2. Click on your location point
                           3. Click "Share" and choose "Embed map" tab
                           4. Copy only URL and paste it within the src="" field below
                    -->

              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d372172.9093396665!2d76.663972677516!3d43.217860527183696!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38836e7d16c5cbab%3A0x3d44668fad986d76!2z0JDQu9C80LDRgtGL!5e0!3m2!1sru!2skz!4v1633511522668!5m2!1sru!2skz" width="100%" height="500px" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <div class="container">
                <form id="contact" action="" method="post">
                  <div class="row">
                    <div class="col-md-6">
                      <fieldset>
                        <input name="name" type="text" class="form-control" id="name" placeholder="Ваше имя..." required="">
                      </fieldset>
                    </div>
                    <div class="col-md-6">
                      <fieldset>
                        <input name="email" type="text" class="form-control" id="email" placeholder="Ваш email..." required="">
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <input name="subject" type="text" class="form-control" id="subject" placeholder="Тема..." required="">
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <textarea name="message" rows="6" class="form-control" id="message" placeholder="Ваше сообщение..." required=""></textarea>
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <button type="submit" id="form-submit" class="button">Отправить</button>
                      </fieldset>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- About Page Ends Here -->
{% endblock %}

{% block js %}
  <script src="assets/js/isotope.js"></script>
  <script src="/static/stepshop/assets/js/flex-slider.js"></script>
{% endblock %}

stepshop/stepshop/templates/stepshop/index.html
{% extends 'stepshop/base.html' %}
{% load static %}
{% load default_image_tags %}

{% block title %}Главная{% endblock %}

{% block content %}
<!-- Page Content -->
<!-- Banner Starts Here -->
<div class="banner">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="caption">
                    <h2>EVILBLOODMACHINE INC.</h2>
                    <div class="line-dec"></div>
                    <p>
                        Крупнейший музыкальный онлайн-магазин у меня в районе.<br><br>
                        Виниловые пластинки, CD-диски и цифровые копии тут вы можете приобрести по цене которую установил исполнитель.
                    </p>
                    <div class="main-button">
                        <a href="{% url 'products:index' %}">Каталог</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Banner Ends Here -->

<!-- Featured Starts Here -->
<div class="featured-items">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-heading">
                    <div class="line-dec"></div>
                    <h1>Интересные предложения</h1>
                </div>
            </div>
            <div class="col-md-12">
                <div class="owl-carousel owl-theme">

                    {% for prod in products %}
                    <a href="{% url 'products:product' prod.pk %}">
                        <div class="featured-item">
                            <img src="{{ prod.image|default_product_image }}"
                         alt="{{ prod.name }}">
                            <h4>{{ prod.name }}</h4>
                            <h6>${{ prod.price }}</h6>
                            <p>{{ prod.category }}</p>
                        </div>
                    </a>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
</div>
<!-- Featred Ends Here -->
{% endblock %}