stepshop/authapp/urls.py
from django.urls import path

from .views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

stepshop/basketapp/urls.py
from django.urls import path

from basketapp.views import basket, basket_add, basket_remove, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>', basket_add, name='add'),
    path('remove/<int:pk>', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit'),
]

stepshop/mainapp/urls.py
from django.urls import path

from .views import products, product

app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
    path('page/<int:page>', products, name='page'),
    path('category/<int:pk>/', products, name='category'),
    path('category/<int:pk>/page/<int:page>/', products, name='category_page'),
    path('product/<int:pk>', product, name='product'),
]

stepshop/stepshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index, contacts, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

# благодаря этой команде все картинки при добавление добавляются в папку media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True,
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    is_active = models.BooleanField(
        default=True,
        verbose_name='Активный',
    )

    def __str__(self):
        return self.name or f'Id категории - {self.pk}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        verbose_name='категория'
    )

    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128,
    )

    image = models.ImageField(
        upload_to='product_images',
        blank=True,
        verbose_name='изображение',
    )

    short_desc = models.CharField(
        verbose_name='краткое описание',
        max_length=128,
        blank=True,
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    price = models.DecimalField(
        verbose_name='цена',
        max_digits=8,
        decimal_places=2,
        default=0,
    )

    quantity = models.PositiveIntegerField(
        verbose_name='количество товара на складе',
        default=0,
    )

    is_active = models.BooleanField(
        default=True,
        verbose_name='Активный',
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name or f'Id продукта - {self.pk}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

stepshop/mainapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from mainapp.models import Product, ProductCategory
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from basketapp.models import Basket


def get_basket(user_):
    if user_.is_authenticated:
        return Basket.objects.filter(user=user_)
    else:
        return []


def get_same_product(current_product):
    return Product.objects.filter(category=current_product.category, is_active=True).exclude(id=current_product.id)


def products(request, pk=None, page=1):
    title = 'продукты | каталог'

    links_menu = ProductCategory.objects.filter(is_active=True)

    products_all = Product.objects.filter(category__is_active=True, is_active=True)
    category = {'name': 'альбомы'}

    if pk is not None:
        products_all = Product.objects.filter(is_active=True, category__id=pk)
        category = get_object_or_404(ProductCategory, id=pk)
        if not category.is_active:
            return HttpResponseRedirect(reverse('products:index'))

    basket = get_basket(request.user)

    paginator = Paginator(products_all, 6)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    context = {
        'title': title,
        'links_menu': links_menu,
        'products': products_paginator,
        'category': category,
        'pk': pk,
        'basket': basket,
    }

    return render(request, 'mainapp/products.html', context)


def product(request, pk):
    title = 'продукт'

    links_menu = ProductCategory.objects.all()
    product_item = get_object_or_404(Product, id=pk)

    category = product_item.category
    if not category.is_active or not product_item.is_active:
        return HttpResponseRedirect(reverse('products:index'))

    basket = get_basket(request.user)
    same_products = get_same_product(product_item)

    context = {
        'title': title,
        'links_menu': links_menu,
        'product': product_item,
        'basket': basket,
        'same_products': same_products,
    }

    return render(request, 'mainapp/product.html', context)

stepshop/mainapp/templates/mainapp/product.html
{% extends 'stepshop/base.html' %}
{% load static %}
{% load default_image_tags %}

{% block css %}
<link rel="stylesheet" href="{% static 'mainapp/style.css' %}">
{% endblock %}

{% block content %}
    <!-- Page Content -->
    <!-- Single Starts Here -->
    <div class="single-product">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>Альбом</h1>
            </div>
          </div>
          <div class="col-md-6">
            <div class="product-slider">
              <div id="slider" class="flexslider">
                <img src="{{ product.image|default_product_image }}" alt="{{ product.name }}" />
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <h4>{{ product.name }}</h4>
              <h6>${{ product.price }}</h6>
              <p>{{ product.description }}</p>


              {#% if user.is_authenticated %#}
              <div class="main-button">
                <a href="{% url 'basket:add' product.pk %}">Заказать</a>
              </div>
              {#% else %#}
<!--              <div class="btn btn-secondary">-->
<!--                <a href="{% url 'basket:add' product.pk %}">Заказать</a>-->
<!--              </div>-->
              {#% endif %#}

              <div class="down-content">
                <div class="categories">
                  <h6>Категория: <span>
                    <a href="{% url 'products:category' product.category.pk %}">
                      {{ product.category }}
                    </a>
                  </span></h6>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Single Page Ends Here -->


    <!-- Similar Starts Here -->
    <div class="featured-items">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>Похожие продукты</h1>
            </div>
          </div>

          <div class="col-md-12">
            <div class="owl-carousel owl-theme">

              {% for product in same_products %}
              <a href="{% url 'products:product' product.pk %}">
                <div class="featured-item">
                  <img src="{{ product.image|default_product_image }}" alt="{{ product.name }}">
                  <h4>{{ product.name }}</h4>
                  <h6>${{ product.price }}</h6>
                </div>
              </a>
              {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Similar Ends Here -->
{% endblock %}

stepshop/mainapp/templates/mainapp/products.html
{% extends 'stepshop/base.html' %}
{% load static %}
{% load default_image_tags %}

{% block title %}Продукты{% endblock %}

{% block content %}
<!-- Page Content -->

<!-- Items Starts Here -->
{% include 'mainapp/includes/inc_category_menu.html' %}

<div class="featured container no-gutter">

    <div class="row posts">
        {% for product in products %}
        <div id="{{ product.id }}" class="item new col-md-4">
            <a href="{% url 'products:product' product.pk %}">
                <div class="featured-item">
                    <img src="{{ product.image|default_product_image }}"
                         alt="{{ product.name }}">
                    <h4>{{ product.name }}</h4>
                    <h6>{{ product.price }}</h6>
                </div>
            </a>
        </div>

        {% endfor %}
    </div>
</div>

{% if products.paginator and products.paginator.num_pages > 1 %}
<div class="page-navigation">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul>
                    {% if products.has_previous %}
                    <li>
                        <a href="
                                {% if pk %}
                                    {% url 'products:category_page' category.pk products.previous_page_number %}
                                {% else %}
                                    {% url 'products:page' products.previous_page_number %}
                                {% endif %}
                                ">
                            <i class="fa fa-angle-left"></i>
                        </a>
                    </li>
                    {% endif %}

                    {% for page in products.paginator.page_range %}
                    <li {% if products.number == page %} class="current-page" {% endif %}>
                        <a href="
                                    {% if pk %}
                                        {% url 'products:category_page' category.pk page %}
                                    {% else %}
                                        {% url 'products:page' page %}
                                    {% endif %}
                                    ">
                            {{ page }}
                        </a>
                    </li>
                    {% endfor %}

                    {% if products.has_next %}
                    <li>
                        <a href="
                                {% if pk %}
                                    {% url 'products:category_page' category.pk products.next_page_number %}
                                {% else %}
                                    {% url 'products:page' products.next_page_number %}
                                {% endif %}
                                ">
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endif %}
<!-- Featred Page Ends Here -->
{% endblock %}